# Set the base image to use
FROM gcc:latest
# Copy the C program into the container
COPY scores.c .
# Compile the C program
RUN gcc -o scores scores.c
# Set the command to run when the container starts
CMD ["./scores"]